# Generated by Django 5.2 on 2025-04-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_certificate_education_workexperience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Sertifikat', 'verbose_name_plural': 'Sertifikatlar'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': "Ta'lim", 'verbose_name_plural': "Ta'limlar"},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': "Ko'nikma", 'verbose_name_plural': "Ko'nikmalar"},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'verbose_name': 'Ish tajribasi', 'verbose_name_plural': 'Ish tajribalari'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.TextField(blank=True, help_text="Qo'shimcha ma'lumotlar"),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issue_date',
            field=models.CharField(help_text='Berilgan sana, masalan: 2023-yil', max_length=50),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issuer',
            field=models.CharField(help_text='Beruvchi tashkilot', max_length=200),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(help_text='Sertifikat nomi', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(help_text='Daraja, masalan: Bakalavr', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, help_text="Qo'shimcha ma'lumotlar"),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.CharField(blank=True, help_text="Tugash sanasi, bo'sh qoldirilsa 'Hozirgacha' ko'rsatiladi", max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(help_text="Ta'lim muassasasi nomi", max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.CharField(help_text='Boshlanish sanasi, masalan: 2016-yil', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='percentage',
            field=models.IntegerField(help_text="Foiz sifatida, 0-100 oralig'ida"),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='company',
            field=models.CharField(help_text='Kompaniya nomi', max_length=200),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='description',
            field=models.TextField(help_text='Ish tavsifi'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.CharField(blank=True, help_text="Tugash sanasi, bo'sh qoldirilsa 'Hozirgacha' ko'rsatiladi", max_length=50),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.CharField(help_text='Boshlanish sanasi, masalan: 2020-yil', max_length=50),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='title',
            field=models.CharField(help_text='Lavozim nomi, masalan: Veb-dasturchi', max_length=200),
        ),
    ]
