# Generated by Django 5.2 on 2025-04-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_certificate_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Profil rasmi (kvadrat shaklda, masalan, 150x150px)', upload_to='profile/')),
            ],
            options={
                'verbose_name': 'Profil rasmi',
                'verbose_name_plural': 'Profil rasmlari',
            },
        ),
    ]
